# auto-generated by setup-desktop.ps1. launched by Task Scheduler.
#   weekdays, every 15 minutes between 09:00 and 15:30 JST.
#   Fetches intraday prices for the holdings + watch list into out/quotes.json
#   and publishes it, so the dashboard can show a live price instead of only
#   the confirmed close.
#
# ASCII only. Do NOT add Japanese: PowerShell 5.1 reads .ps1 as Shift-JIS.
#
# Why this script exists at all: src/quotes.py was written but never wired to
# any scheduler, so the published out/quotes.json sat frozen at 2026-08-05 for
# three weeks while the dashboard presented it as the current price.

Set-Location "$env:USERPROFILE\morning-report"
$log = "$env:USERPROFILE\morning-report\out\task.log"
New-Item -ItemType Directory -Force -Path (Split-Path $log) | Out-Null

function Log($m) { "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] quotes: $m" | Add-Content $log }

# Market-hours guard. The trigger already limits this, but a manual or stray run
# outside trading hours must not push a duplicate of the closing price.
# Holidays are not detected here; on a holiday yfinance simply returns the last
# session's bar, the payload does not change, and nothing is committed.
$now = Get-Date
if ($now.DayOfWeek -eq "Saturday" -or $now.DayOfWeek -eq "Sunday") { exit 0 }
$t = $now.TimeOfDay
if ($t -lt [TimeSpan]"09:00:00" -or $t -gt [TimeSpan]"15:35:00") { exit 0 }

# Deliberately NOT doing "git reset --hard origin/main" here.
# run-daily.ps1 does that once a day, which is safe. Doing it every 15 minutes
# would discard a dashboard.json that the 08:30 run had just produced but not
# yet pushed.

& ".\.venv\Scripts\python.exe" "src\quotes.py" --once 2>&1 | Add-Content $log
$rc = $LASTEXITCODE
if ($rc -ne 0) { Log "python exit=$rc - skip publish"; exit $rc }

# Commit only when a PRICE actually changed.
# out/quotes.json always carries generated_at_jst, which differs on every run,
# so a plain "did the file change" test would commit ~26 times a day even during
# the lunch break when no price moved. Compare the diff while ignoring that one
# field: if nothing else changed, put the file back and do nothing.
$diff = git diff -U0 -- out/quotes.json
$real = $diff | Where-Object {
    $_ -match '^[+-]' -and $_ -notmatch '^(\+\+\+|---)' -and $_ -notmatch 'generated_at_jst'
}
if (-not $real) {
    git checkout -- out/quotes.json 2>&1 | Out-Null
    exit 0
}

git add out/quotes.json 2>&1 | Out-Null
git -c user.email="local@example.com" -c user.name="local" commit -q -m "quotes: $(Get-Date -Format 'yyyy-MM-dd HH:mm') intraday"
git push --quiet 2>&1 | Out-Null
if ($LASTEXITCODE -ne 0) {
    # Someone else (the 08:30 / 16:00 run, or the Actions workflow) pushed first.
    # Rebase and retry once. If this still fails, leave the commit local and say
    # so loudly: run-daily.ps1 does "git reset --hard origin/main", which would
    # silently discard it on the next scheduled run.
    Log "push rejected - rebasing"
    git pull --rebase --quiet origin main 2>&1 | Out-Null
    git push --quiet 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Log "WARN: push still failing - commit is LOCAL ONLY and run-daily.ps1 will discard it"
        exit 1
    }
}
Log "pushed"
